version: "2"
checks:
  argument-count:
    enabled: false
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 50
plugins:
  # ... CONFIG CONTENT ...
  phpmd:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      Design/LongParameterList:
        enabled: false
# ... CONFIG CONTENT ...
