services:
    # Admin Controllers
    ganstaz.gzo.admin_controller:
        class: ganstaz\gzo\src\controller\admin\index_controller
        shared: false
        parent: ganstaz.gzo.abstract_controller

    ganstaz.gzo.admin.settings_controller:
        class: ganstaz\gzo\src\controller\admin\settings
        shared: false
        parent: ganstaz.gzo.abstract_controller
        arguments:
            - '@ganstaz.gzo.settings'
