services:
    ganstaz.gzo.area.loader:
        class: ganstaz\gzo\src\area\loader
        arguments:
            - '@ganstaz.gzo.area_collection'

    kernel_controller_arguments_area_navigation_subscriber:
        class: ganstaz\gzo\src\area\event\area_navigation
        arguments:
            - '@ganstaz.gzo.area.loader'
        tags:
            - { name: kernel.event_subscriber }

# ----- Area -----
    ganstaz.gzo.area_collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: gzo.area }

    ganstaz.gzo.area.base:
        abstract: true
        arguments:
            - '@auth'
            - '@cache'
            - '@dbal.conn'
            - '@event_dispatcher'
            - '@template'
            - '@ganstaz.gzo.controller.helper'
            - '%core.table_prefix%'

    ganstaz.gzo.area:
        class: ganstaz\gzo\src\area\type\gzo
        shared: false
        parent: ganstaz.gzo.area.base
        calls:
            - [set_type, [gzo]]
        tags:
            - { name: gzo.area }
