services:
    ganstaz.web.block.manager:
        class: ganstaz\web\core\blocks\manager
        arguments:
            - '@dbal.conn'
            - '@ganstaz.web.block.collection'
            - '@ganstaz.web.block.event'
            - '%ganstaz.web.tables.blocks%'

    ganstaz.web.block.collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: gz.web.block }

    ganstaz.web.block.event:
        class: ganstaz\web\core\blocks\event

    ganstaz.web.block.base:
        abstract: true
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@template'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'

# ----- Blocks -----
    ganstaz.web.block.news:
        class: ganstaz\web\core\blocks\type\news
        shared: false
        parent: ganstaz.web.block.base
        arguments:
            - '@auth'
            - '@language'
            - '@text_formatter.renderer'
            - '@user'
            - '@pagination'
        calls:
            - [set_active, [false]]
            - [set_special, [true]]
        tags:
            - { name: gz.web.block }

    ganstaz.web.block.mini.profile:
        class: ganstaz\web\core\blocks\type\mini_profile
        shared: false
        parent: ganstaz.web.block.base
        calls:
            - [set_active, [false]]
            - [set_special, [false]]
        tags:
            - { name: gz.web.block }

    ganstaz.web.block.information:
        class: ganstaz\web\core\blocks\type\information
        shared: false
        parent: ganstaz.web.block.base
        calls:
            - [set_active, [true]]
            - [set_special, [true]]
        tags:
            - { name: gz.web.block }

    ganstaz.web.block.the.team:
        class: ganstaz\web\core\blocks\type\the_team
        shared: false
        parent: ganstaz.web.block.base
        calls:
            - [set_active, [true]]
            - [set_special, [true]]
        tags:
            - { name: gz.web.block }

    ganstaz.web.block.top.posters:
        class: ganstaz\web\core\blocks\type\top_posters
        shared: false
        parent: ganstaz.web.block.base
        calls:
            - [set_active, [true]]
            - [set_special, [true]]
        tags:
            - { name: gz.web.block }

    ganstaz.web.block.recent.posts:
        class: ganstaz\web\core\blocks\type\recent_posts
        shared: false
        parent: ganstaz.web.block.base
        calls:
            - [set_active, [true]]
            - [set_special, [true]]
        tags:
            - { name: gz.web.block }

    ganstaz.web.block.recent.topics:
        class: ganstaz\web\core\blocks\type\recent_topics
        shared: false
        parent: ganstaz.web.block.base
        calls:
            - [set_active, [true]]
            - [set_special, [true]]
        tags:
            - { name: gz.web.block }

    ganstaz.web.block.whos.online:
        class: ganstaz\web\core\blocks\type\whos_online
        shared: false
        parent: ganstaz.web.block.base
        arguments:
            - '@auth'
            - '@user'
        calls:
            - [set_active, [true]]
            - [set_special, [false]]
        tags:
            - { name: gz.web.block }
