services:
    dls.web.block.manager:
        class: dls\web\core\blocks\manager
        arguments:
            - '@dbal.conn'
            - '@dls.web.block.collection'
            - '@dls.web.block.event'
            - '%dls.web.tables.blocks%'

    dls.web.admin.block.controller:
        class: dls\web\controller\admin_block_controller
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@dls.web.block.manager'
            - '@dls.web.helper'
            - '@cache'

    dls.web.block.collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: dls.web.block }

    dls.web.block.event:
        class: dls\web\core\blocks\event

    dls.web.block.extension:
        class: dls\web\core\twig\extension
        arguments:
            - '@dls.web.block.event'
        tags:
            - { name: twig.extension }

# ----- Blocks -----
    dls.web.block.mini.profile:
        class: dls\web\core\blocks\block\mini_profile
        tags:
            - { name: dls.web.block }

    dls.web.block.information:
        class: dls\web\core\blocks\block\information
        arguments:
            - '@config'
            - '@template'
            - '@dispatcher'
        tags:
            - { name: dls.web.block }

    dls.web.block.the.team:
        class: dls\web\core\blocks\block\the_team
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@dls.web.helper'
        tags:
            - { name: dls.web.block }

    dls.web.block.top.posters:
        class: dls\web\core\blocks\block\top_posters
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@template'
        tags:
            - { name: dls.web.block }

    dls.web.block.recent.posts:
        class: dls\web\core\blocks\block\recent_posts
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@dls.web.helper'
        tags:
            - { name: dls.web.block }

    dls.web.block.recent.topics:
        class: dls\web\core\blocks\block\recent_topics
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@dls.web.helper'
        tags:
            - { name: dls.web.block }

    dls.web.block.whos.online:
        class: dls\web\core\blocks\block\whos_online
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@dls.web.helper'
            - '@dispatcher'
        tags:
            - { name: dls.web.block }
