services:
    dls.web.blocks.manager:
        class: dls\web\core\blocks\block_manager
        arguments:
            - '@dbal.conn'
            - '@dls.web.blocks.collection'
            - '%dls.web.tables.blocks%'
            - '%dls.web.tables.blocks_data%'
            - '@dls.web.helper'
            - '@dls.web.blocks.template.data'

    dls.web.blocks.collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: dls.web.blocks }

    dls.web.blocks.template.data:
        class: dls\web\core\blocks\template_data

    dls.web.blocks.extension:
        class: dls\web\core\twig\extension
        arguments:
            - '@dls.web.blocks.template.data'
        tags:
            - { name: twig.extension }

# ----- Blocks -----
    dls.web.block.mini.profile:
        class: dls\web\core\blocks\block\mini_profile
        tags:
            - { name: dls.web.blocks }

    dls.web.block.information:
        class: dls\web\core\blocks\block\information
        arguments:
            - '@config'
            - '@template'
            - '@dispatcher'
        tags:
            - { name: dls.web.blocks }

    dls.web.block.the.team:
        class: dls\web\core\blocks\block\the_team
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '@dls.web.helper'
        tags:
            - { name: dls.web.blocks }

    dls.web.block.top.posters:
        class: dls\web\core\blocks\block\top_posters
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@template'
        tags:
            - { name: dls.web.blocks }

    dls.web.block.recent.posts:
        class: dls\web\core\blocks\block\recent_posts
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '@dls.web.helper'
            - '%core.root_path%'
        tags:
            - { name: dls.web.blocks }

    dls.web.block.recent.topics:
        class: dls\web\core\blocks\block\recent_topics
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '@dls.web.helper'
            - '%core.root_path%'
        tags:
            - { name: dls.web.blocks }

    dls.web.block.whos.online:
        class: dls\web\core\blocks\block\whos_online
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@template'
            - '@dls.web.helper'
            - '@dispatcher'
            - '%core.root_path%'
        tags:
            - { name: dls.web.blocks }
