services:
    # Controllers
    ganstaz.gzo.abstract_controller:
        abstract: true
        arguments:
            - '@config'
            - '@event_dispatcher'
            - '@language'
            - '@template'
            - '@user'
            - '@ganstaz.gzo.controller.helper'
            - '@ganstaz.gzo.entity.manager'
            - '@ganstaz.gzo.form'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.gzo.index_controller:
        class: ganstaz\gzo\src\controller\index
        shared: false
        parent: ganstaz.gzo.abstract_controller
        arguments:
            - '@ganstaz.gzo.posts'

    ganstaz.gzo.articles_controller:
        class: ganstaz\gzo\src\controller\articles
        shared: false
        parent: ganstaz.gzo.abstract_controller
        arguments:
            - '@ganstaz.gzo.posts'

    ganstaz.gzo.forum_controller:
        class: ganstaz\gzo\src\controller\forum
        shared: false
        parent: ganstaz.gzo.abstract_controller
        arguments:
            - '@ganstaz.gzo.main'

    ganstaz.gzo.post_controller:
        class: ganstaz\gzo\src\controller\post
        shared: false
        parent: ganstaz.gzo.abstract_controller

    ganstaz.gzo.posts_controller:
        class: ganstaz\gzo\src\controller\posts_controller
        shared: false
        parent: ganstaz.gzo.abstract_controller
