services:
    ganstaz.gzo.entity.manager:
        class: ganstaz\gzo\core\entity\manager
        arguments:
            - '@ganstaz.gzo.entity.type_collection'
            - '@cache'

    ganstaz.gzo.entity.type_collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: gzo.entity.type }

# ----- Types -----
    ganstaz.gzo.entity.type.config:
        class: ganstaz\gzo\core\entity\type\config
        shared: false
        arguments:
            - '@config'
        tags:
            - { name: gzo.entity.type }

    # ganstaz.gzo.entity.type.db:
    #     class: ganstaz\gzo\core\entity\type\db
    #     shared: false
    #     arguments:
    #         - '@dbal.conn'
    #     tags:
    #         - { name: gzo.entity.type }

    # ganstaz.gzo.entity.type.config_text:
    #     class: ganstaz\gzo\core\entity\type\config_text
    #     shared: false
    #     arguments:
    #         - '@config_text'
    #     tags:
    #         - { name: gzo.entity.type }
