services:
    kernel_controller_arguments_auth_attribute_subscriber:
        class: ganstaz\gzo\src\security\event\auth_attribute
        arguments:
            - '@ganstaz.gzo.security.check_auth'
            - '@ganstaz.gzo.area.loader'
        tags:
            - { name: kernel.event_subscriber }

    # kernel_request_subscriber:
    #     class: ganstaz\gzo\src\event\kernel_request
    #     arguments:
    #         - '@ganstaz.gzo.check_auth'
    #         - '@ganstaz.gzo.area.loader'
    #     tags:
    #         - { name: kernel.event_subscriber }

    ganstaz.gzo.subscribers:
        class: ganstaz\gzo\src\event\subscribers
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.gzo.plugin.loader'
            - '@ganstaz.gzo.helper'
            - '@ganstaz.gzo.page'
            - '@ganstaz.gzo.users_loader'
        tags:
            - { name: event.listener }
