services:
    kernel_controller_arguments_auth_attribute_subscriber:
        class: ganstaz\gzo\src\security\event\auth_attribute
        arguments:
            - '@ganstaz.gzo.security.check_auth'
        tags:
            - { name: kernel.event_subscriber }

    ganstaz.gzo.subscribers:
        class: ganstaz\gzo\src\event\subscribers
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.gzo.plugin.loader'
            - '@ganstaz.gzo.helper'
            - '@ganstaz.gzo.page'
            - '@ganstaz.gzo.users_loader'
        tags:
            - { name: event.listener }
