services:
    kernel_request_subscriber:
        class: ganstaz\gzo\src\event\kernel_request
        arguments:
            - '@ganstaz.gzo.auth'
            - '@ganstaz.gzo.area.loader'
        tags:
            - { name: kernel.event_subscriber }

    ganstaz.gzo.subscribers:
        class: ganstaz\gzo\src\event\subscribers
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.gzo.blocks.loader'
            - '@ganstaz.gzo.helper'
            - '@ganstaz.gzo.pages'
            - '@ganstaz.gzo.users_loader'
        tags:
            - { name: event.listener }
