gzo_main:
    path: /index
    controller: ganstaz.gzo.admin_controller:index

gzo_settings:
    path: /gzo-settings
    controller: ganstaz.gzo.admin_controller:index

gzo_pages:
    path: /gzo-pages
    controller: ganstaz.gzo.admin_controller:index

gzo_plugins:
    path: /gzo-plugins
    controller: ganstaz.gzo.admin_controller:index
