services:
    # Admin Controllers
    ganstaz.gzo.admin_controller:
        class: ganstaz\gzo\src\controller\admin\index
        shared: false
        parent: ganstaz.gzo.abstract_controller
        arguments:
            - '@config'

    ganstaz.gzo.admin.settings_controller:
        class: ganstaz\gzo\src\controller\admin\settings
        shared: false
        parent: ganstaz.gzo.abstract_controller
        arguments:
            - '@ganstaz.gzo.settings'

    ganstaz.gzo.admin.blocks_controller:
        class: ganstaz\gzo\src\controller\admin\blocks
        shared: false
        parent: ganstaz.gzo.abstract_controller
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.gzo.blocks.manager'

    ganstaz.gzo.admin.pages_controller:
        class: ganstaz\gzo\src\controller\admin\pages
        shared: false
        parent: ganstaz.gzo.abstract_controller
        arguments:
            - '@cache'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '%ganstaz.gzo.tables.pages%'

# To be removed
    ganstaz.gzo.admin.old.block_controller:
        class: ganstaz\gzo\src\controller\old\blocks
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.gzo.blocks.manager'

    ganstaz.gzo.admin.old.page_controller:
        class: ganstaz\gzo\src\controller\old\pages
        arguments:
            - '@cache'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '%ganstaz.gzo.tables.pages%'
