services:
    ganstaz.gzo.tabs_collection:
        class: phpbb\di\ordered_service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: gzo.tab.type }

    ganstaz.gzo.tabs.manager:
        class: ganstaz\gzo\src\tabs\manager
        arguments:
            - '@ganstaz.gzo.tabs_collection'
            - '@controller.helper'
            - '@language'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.gzo.tab.base:
        abstract: true
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@dispatcher'
            - '@controller.helper'
            - '@language'
            - '@template'
            - '@user'

# ----- GZO Tabs -----
    ganstaz.gzo.tab.profile:
        class: ganstaz\gzo\src\tabs\type\profile
        shared: false
        parent: ganstaz.gzo.tab.base
        arguments:
            - '@config'
            - '@group_helper'
            - '@profilefields.manager'
            - '%core.adm_relative_path%'
            - '%core.root_path%'
            - '%core.php_ext%'
        calls:
            - [set_name, [profile]]
        tags:
            - { name: gzo.tab.type, order: 1 }

# ----- Controllers -----
    ganstaz.gzo.profile_controller:
        class: ganstaz\gzo\src\controller\member\profile
        arguments:
            - '@controller.helper'
            - '@language'
            - '@template'
            - '@?ganstaz.gzo.tabs.manager'
