services:
    ganstaz.web.plugin.collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: gz.web.plugin }

    ganstaz.web.plugin.manager:
        class: ganstaz\web\core\plugins\manager
        arguments:
            - '@ganstaz.web.plugin.collection'

# ----- GZ Web Plugins -----
# Achievements
    ganstaz.web.plugin.level:
        class: ganstaz\web\core\plugins\user\level
        tags:
            - { name: gz.web.plugin }
