services:
    ganstaz.gzo.plugin.loader:
        class: ganstaz\gzo\src\plugin\loader
        arguments:
            - '@dbal.conn'
            - '@ganstaz.gzo.plugin.collection'
            - '@ganstaz.gzo.plugin.data'
            - '%ganstaz.gzo.tables.plugins%'
            - '%ganstaz.gzo.tables.plugins_on_page%'

    ganstaz.gzo.plugin.data:
        class: ganstaz\gzo\src\plugin\data

    ganstaz.gzo.plugin.base:
        abstract: true
        arguments:
            - '@config'
            - '@controller.helper'
            - '@dbal.conn'
            - '@event_dispatcher'
            - '@template'
            - '@ganstaz.gzo.users_loader'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.gzo.posts:
        class: ganstaz\gzo\src\plugin\article\posts
        shared: false
        parent: ganstaz.gzo.plugin.base
        arguments:
            - '@auth'
            - '@language'
            - '@pagination'
            - '@text_formatter.renderer'
            - '@user'
            - '@ganstaz.gzo.helper'

# ----- Plugins -----
    ganstaz.gzo.plugin.collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: gzo.plugin }

    ganstaz.gzo.plugin.announcement:
        class: ganstaz\gzo\src\plugin\announcement\announcement
        shared: false
        parent: ganstaz.gzo.plugin.base
        calls:
            - [is_loadable, [false]]
        tags:
            - { name: gzo.plugin }

    ganstaz.gzo.plugin.mini_profile:
        class: ganstaz\gzo\src\plugin\blocks\mini_profile
        shared: false
        parent: ganstaz.gzo.plugin.base
        calls:
            - [is_loadable, [false]]
        tags:
            - { name: gzo.plugin }

    ganstaz.gzo.plugin.information:
        class: ganstaz\gzo\src\plugin\blocks\information
        shared: false
        parent: ganstaz.gzo.plugin.base
        calls:
            - [is_loadable, [true]]
        tags:
            - { name: gzo.plugin }

    ganstaz.gzo.plugin.the_team:
        class: ganstaz\gzo\src\plugin\blocks\the_team
        shared: false
        parent: ganstaz.gzo.plugin.base
        calls:
            - [is_loadable, [true]]
        tags:
            - { name: gzo.plugin }

    ganstaz.gzo.plugin.top_posters:
        class: ganstaz\gzo\src\plugin\blocks\top_posters
        shared: false
        parent: ganstaz.gzo.plugin.base
        calls:
            - [is_loadable, [true]]
        tags:
            - { name: gzo.plugin }

    ganstaz.gzo.plugin.recent_posts:
        class: ganstaz\gzo\src\plugin\blocks\recent_posts
        shared: false
        parent: ganstaz.gzo.plugin.base
        calls:
            - [is_loadable, [true]]
        tags:
            - { name: gzo.plugin }

    ganstaz.gzo.plugin.recent_topics:
        class: ganstaz\gzo\src\plugin\blocks\recent_topics
        shared: false
        parent: ganstaz.gzo.plugin.base
        calls:
            - [is_loadable, [true]]
        tags:
            - { name: gzo.plugin }

    ganstaz.gzo.plugin.whos_online:
        class: ganstaz\gzo\src\plugin\blocks\whos_online
        shared: false
        parent: ganstaz.gzo.plugin.base
        arguments:
            - '@ganstaz.gzo.info'
        calls:
            - [is_loadable, [true]]
        tags:
            - { name: gzo.plugin }
