services:
    dls.web.plugin.collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: dls.web.plugin }

    dls.web.plugin.manager:
        class: dls\web\core\plugins\manager
        arguments:
            - '@dls.web.plugin.collection'

# ----- Dls Web Plugins -----
# Achievements
    dls.web.plugin.level:
        class: dls\web\core\plugins\user\level
        tags:
            - { name: dls.web.plugin }
