services:
    dls.web.plugin.manager:
        class: dls\web\core\plugin\manager
        arguments:
            - '@dls.web.plugin.collection'

    dls.web.plugin.collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: dls.web.plugin }

    dls.web.level.plugin:
        class: dls\web\core\plugin\user\level
        calls:
            - [set_name, [level]]
        tags:
            - { name: dls.web.plugin }
