ganstaz_gzo_index:
    path: /
    defaults: { _controller: ganstaz.gzo.index_controller:handle }

ganstaz_gzo_forum:
    path: /forum
    defaults: { _controller: ganstaz.gzo.forum_controller:handle }

ganstaz_gzo_news:
    path: /news/{id}
    defaults: { _controller: ganstaz.gzo.articles_controller:handle, id: 3, page: 1 }
    requirements:
        id: \d+

ganstaz_gzo_news_page:
    path: /news/{id}/page/{page}
    defaults: { _controller: ganstaz.gzo.articles_controller:handle }
    requirements:
        id: \d+
        page: \d+

ganstaz_gzo_article:
    path: /article-full/{aid}
    defaults: { _controller: ganstaz.gzo.articles_controller:article }
    requirements:
        aid: \d+

ganstaz_gzo_first_post:
    path: /article/{aid}
    defaults: { _controller: ganstaz.gzo.articles_controller:first_post }
    requirements:
        aid: \d+

ganstaz_gzo_post_article:
    path: /post/article/{fid}
    defaults: { _controller: ganstaz.gzo.post_controller:handle }
    requirements:
        fid: \d+

ganstaz_gzo_member:
    path: /u/{username}
    defaults: { _controller: ganstaz.gzo.profile_controller:handle, tab: profile }

ganstaz_gzo_member_tab:
    path: /u/{username}/tab/{tab}
    defaults:
        _controller: ganstaz.gzo.profile_controller:handle
