ganstaz_web_news_base:
    path: /news/{id}
    defaults: { _controller: ganstaz.web.news.controller:handle, id: 3, page: 1 }
    requirements:
        id: \d+

ganstaz_web_news_page:
    path: /news/{id}/page/{page}
    defaults: { _controller: ganstaz.web.news.controller:handle }
    requirements:
        id: \d+
        page: \d+

ganstaz_web_article:
    path: /article/{aid}
    defaults: { _controller: ganstaz.web.news.controller:article }
    requirements:
        aid: \d+
