imports:
    - { resource: blocks.yml }
    - { resource: entity.yml }
    - { resource: member.yml }
    - { resource: tables.yml }

services:
    ganstaz.gzo.helper:
        class: ganstaz\gzo\core\helper
        arguments:
            - '@dbal.conn'

    ganstaz.gzo.info:
        class: ganstaz\gzo\core\info
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.gzo.pages:
        class: ganstaz\gzo\core\pages
        arguments:
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%ganstaz.gzo.tables.pages%'
            - '%core.php_ext%'

    ganstaz.gzo.time:
        class: ganstaz\gzo\core\time
        arguments:
            - '@language'

    ganstaz.gzo.listener:
        class: ganstaz\gzo\event\listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.gzo.helper'
            - '@ganstaz.gzo.pages'
            - '@?ganstaz.gzo.block.manager'
        tags:
            - { name: event.listener }

# ----- Twig extensions -----
    ganstaz.gzo.extension:
        class: ganstaz\gzo\core\twig\extension
        arguments:
            - '@template.twig.environment'
            - '@ganstaz.gzo.block.event'
            - '@group_helper'
        tags:
            - { name: twig.extension }

    ganstaz.gzo.form.extension:
        class: ganstaz\gzo\core\twig\extension\form
        tags:
            - { name: twig.extension }

# ----- Models -----
    ganstaz.gzo.main:
        class: ganstaz\gzo\model\main
        arguments:
            - '@auth'
            - '@config'
            - '@dispatcher'
            - '@controller.helper'
            - '@language'
            - '@notification_manager'
            - '@request'
            - '@template'
            - '@user'
            - '@ganstaz.gzo.info'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.gzo.posts:
        class: ganstaz\gzo\model\posts
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@controller.helper'
            - '@language'
            - '@pagination'
            - '@text_formatter.renderer'
            - '@template'
            - '@user'
            - '@ganstaz.gzo.helper'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.gzo.settings:
        class: ganstaz\gzo\model\admin\settings
        arguments:
            - '@ganstaz.gzo.helper'

# ----- Controllers -----
    ganstaz.gzo.abstract.controller:
        abstract: true
        arguments:
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.gzo.entity.manager'

    ganstaz.gzo.controller.base:
        abstract: true
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@user'
            - '@ganstaz.gzo.posts'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.gzo.index.controller:
        class: ganstaz\gzo\controller\index
        shared: false
        parent: ganstaz.gzo.controller.base

    ganstaz.gzo.articles.controller:
        class: ganstaz\gzo\controller\articles
        shared: false
        parent: ganstaz.gzo.controller.base

    ganstaz.gzo.forum.controller:
        class: ganstaz\gzo\controller\forum
        shared: false
        parent: ganstaz.gzo.controller.base
        arguments:
            - '@dispatcher'
            - '@ganstaz.gzo.main'

    ganstaz.gzo.post.controller:
        class: ganstaz\gzo\controller\post
        shared: false
        parent: ganstaz.gzo.controller.base

# ----- Admin Controllers -----
    ganstaz.gzo.admin.settings_controller:
        class: ganstaz\gzo\controller\admin\settings
        shared: false
        parent: ganstaz.gzo.abstract.controller
        arguments:
            - '@ganstaz.gzo.settings'

    ganstaz.gzo.admin.block.controller:
        class: ganstaz\gzo\controller\admin\blocks
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.gzo.block.manager'

    ganstaz.gzo.admin.page.controller:
        class: ganstaz\gzo\controller\admin\pages
        arguments:
            - '@cache'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '%ganstaz.gzo.tables.pages%'
