imports:
    - { resource: blocks.yml }
    - { resource: member.yml }
    - { resource: tables.yml }

services:
    ganstaz.web.helper:
        class: ganstaz\web\core\helper
        arguments:
            - '@dbal.conn'

    ganstaz.web.info:
        class: ganstaz\web\core\info
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.web.pages:
        class: ganstaz\web\core\pages
        arguments:
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%ganstaz.web.tables.pages%'
            - '%core.php_ext%'

    ganstaz.web.time:
        class: ganstaz\web\core\time
        arguments:
            - '@language'

    ganstaz.web.listener:
        class: ganstaz\web\event\listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.web.helper'
            - '@ganstaz.web.pages'
            - '@?ganstaz.web.block.manager'
        tags:
            - { name: event.listener }

    ganstaz.web.extension:
        class: ganstaz\web\core\twig\extension
        arguments:
            - '@template.twig.environment'
            - '@ganstaz.web.block.event'
            - '@group_helper'
        tags:
            - { name: twig.extension }

    ganstaz.web.form.extension:
        class: ganstaz\web\core\twig\extension\form
        tags:
            - { name: twig.extension }

# ----- Models -----
    ganstaz.web.main:
        class: ganstaz\web\model\main
        arguments:
            - '@auth'
            - '@config'
            - '@dispatcher'
            - '@controller.helper'
            - '@language'
            - '@notification_manager'
            - '@request'
            - '@template'
            - '@user'
            - '@ganstaz.web.info'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.web.posts:
        class: ganstaz\web\model\posts
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@controller.helper'
            - '@language'
            - '@pagination'
            - '@text_formatter.renderer'
            - '@template'
            - '@user'
            - '@ganstaz.web.helper'
            - '%core.root_path%'
            - '%core.php_ext%'

# ----- Controllers -----
    ganstaz.web.controller.base:
        abstract: true
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@user'
            - '@ganstaz.web.posts'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.web.index.controller:
        class: ganstaz\web\controller\index
        shared: false
        parent: ganstaz.web.controller.base

    ganstaz.web.articles.controller:
        class: ganstaz\web\controller\articles
        shared: false
        parent: ganstaz.web.controller.base

    ganstaz.web.forum.controller:
        class: ganstaz\web\controller\forum
        shared: false
        parent: ganstaz.web.controller.base
        arguments:
            - '@dispatcher'
            - '@ganstaz.web.main'

    ganstaz.web.post.controller:
        class: ganstaz\web\controller\post
        shared: false
        parent: ganstaz.web.controller.base

# ----- Admin Controllers -----
    ganstaz.web.admin.controller:
        class: ganstaz\web\controller\admin\settings
        arguments:
            - '@config'
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.web.helper'

    ganstaz.web.admin.block.controller:
        class: ganstaz\web\controller\admin\blocks
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.web.block.manager'

    ganstaz.web.admin.page.controller:
        class: ganstaz\web\controller\admin\pages
        arguments:
            - '@cache'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '%ganstaz.web.tables.pages%'
