imports:
    - { resource: blocks.yml }
    - { resource: tables.yml }

services:
    ganstaz.web.helper:
        class: ganstaz\web\core\helper
        arguments:
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%ganstaz.web.tables.pages%'
            - '%core.php_ext%'

    ganstaz.web.time:
        class: ganstaz\web\core\gz_time
        arguments:
            - '@language'

    ganstaz.web.listener:
        class: ganstaz\web\event\listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.web.helper'
            - '@?ganstaz.web.block.manager'
        tags:
            - { name: event.listener }

    ganstaz.web.extension:
        class: ganstaz\web\core\twig\extension
        arguments:
            - '@template.twig.environment'
            - '@ganstaz.web.block.event'
            - '@group_helper'
        tags:
            - { name: twig.extension }

# ----- Controllers -----
    ganstaz.web.controller.base:
        abstract: true
        arguments:
            - '@controller.helper'
            - '@language'
            - '@ganstaz.web.block.manager'

    ganstaz.web.admin.controller:
        class: ganstaz\web\controller\admin_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'

    ganstaz.web.admin.block.controller:
        class: ganstaz\web\controller\admin_block_controller
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@ganstaz.web.block.manager'

    ganstaz.web.admin.page.controller:
        class: ganstaz\web\controller\admin_page_controller
        arguments:
            - '@cache'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '%ganstaz.web.tables.pages%'

    ganstaz.web.news.controller:
        class: ganstaz\web\controller\news_controller
        shared: false
        parent: ganstaz.web.controller.base
