imports:
    - { resource: admin.yml }
    - { resource: area.yml }
    - { resource: controller.yml }
    - { resource: entity.yml }
    - { resource: event.yml }
    - { resource: member.yml }
    - { resource: plugins.yml }
    - { resource: tables.yml }
    - { resource: twig.yml }

services:
    ganstaz.gzo.auth:
        class: ganstaz\gzo\src\auth\auth
        arguments:
            - '@service_container'
            - '@auth'

    ganstaz.gzo.controller.helper:
        class: ganstaz\gzo\src\helper\controller_helper
        decorates: controller.helper
        arguments:
            - '@auth'
            - '@cache.driver'
            - '@config'
            - '@cron.manager'
            - '@dbal.conn'
            - '@event_dispatcher'
            - '@language'
            - '@request'
            - '@routing.helper'
            - '@symfony_request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
            - '%debug.sql_explain%'

    ganstaz.gzo.form:
        class: ganstaz\gzo\src\form\form
        arguments:
            - '@request'
            - '@template'

    ganstaz.gzo.helper:
        class: ganstaz\gzo\src\helper
        arguments:
            - '@dbal.conn'

    ganstaz.gzo.info:
        class: ganstaz\gzo\src\info
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@event_dispatcher'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.gzo.page:
        class: ganstaz\gzo\src\user\page
        arguments:
            - '@config'
            - '@user'
            - '%core.php_ext%'

    ganstaz.gzo.time:
        class: ganstaz\gzo\src\time
        arguments:
            - '@language'

    ganstaz.gzo.users_loader:
        class: ganstaz\gzo\src\user\loader
        arguments:
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.users%'

# ----- Models -----
    ganstaz.gzo.main:
        class: ganstaz\gzo\src\model\main
        arguments:
            - '@auth'
            - '@config'
            - '@event_dispatcher'
            - '@controller.helper'
            - '@language'
            - '@notification_manager'
            - '@request'
            - '@template'
            - '@user'
            - '@ganstaz.gzo.info'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.gzo.settings:
        class: ganstaz\gzo\src\model\admin\settings
        arguments:
            - '@ganstaz.gzo.helper'
