imports:
    - { resource: area.yml }
    - { resource: blocks.yml }
    - { resource: controller.yml }
    - { resource: entity.yml }
    - { resource: event.yml }
    - { resource: gzo.yml }
    - { resource: member.yml }
    - { resource: tables.yml }

services:
    ganstaz.gzo.form:
        class: ganstaz\gzo\src\form\form
        arguments:
            - '@request'
            - '@template'

    ganstaz.gzo.helper:
        class: ganstaz\gzo\src\helper
        arguments:
            - '@dbal.conn'

    ganstaz.gzo.info:
        class: ganstaz\gzo\src\info
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.gzo.pages:
        class: ganstaz\gzo\src\pages
        arguments:
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%ganstaz.gzo.tables.pages%'
            - '%core.php_ext%'

    ganstaz.gzo.time:
        class: ganstaz\gzo\src\time
        arguments:
            - '@language'

# ----- Twig extensions -----
    ganstaz.gzo.extension:
        class: ganstaz\gzo\src\twig\extension
        arguments:
            - '@template.twig.environment'
            - '@ganstaz.gzo.block.event'
            - '@group_helper'
        tags:
            - { name: twig.extension }

    ganstaz.gzo.form.extension:
        class: ganstaz\gzo\src\twig\extension\form
        tags:
            - { name: twig.extension }

# ----- Models -----
    ganstaz.gzo.main:
        class: ganstaz\gzo\src\model\main
        arguments:
            - '@auth'
            - '@config'
            - '@dispatcher'
            - '@controller.helper'
            - '@language'
            - '@notification_manager'
            - '@request'
            - '@template'
            - '@user'
            - '@ganstaz.gzo.info'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.gzo.posts:
        class: ganstaz\gzo\src\model\posts
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@controller.helper'
            - '@language'
            - '@pagination'
            - '@text_formatter.renderer'
            - '@template'
            - '@user'
            - '@ganstaz.gzo.helper'
            - '%core.root_path%'
            - '%core.php_ext%'

    ganstaz.gzo.settings:
        class: ganstaz\gzo\src\model\admin\settings
        arguments:
            - '@ganstaz.gzo.helper'
