imports:
    - { resource: blocks.yml }
    - { resource: plugins.yml }
    - { resource: tables.yml }

services:
    dls.web.helper:
        class: dls\web\core\helper
        arguments:
            - '@group_helper'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'

    dls.web.lunar:
        class: dls\web\core\lunar

    dls.web.listener:
        class: dls\web\event\listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@dls.web.plugin.manager'
        tags:
            - { name: event.listener }

    dls.web.admin.controller:
        class: dls\web\controller\admin_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@dls.web.helper'

    dls.web.news.controller:
        class: dls\web\controller\news_controller
        arguments:
            - '@controller.helper'
            - '@language'
            - '@dls.web.block.manager'
