services:
    ganstaz.gzo.extension:
        class: ganstaz\gzo\src\twig\extension
        arguments:
            - '@template.twig.environment'
            - '@group_helper'
        tags:
            - { name: twig.extension }

    ganstaz.gzo.user.extension:
        class: ganstaz\gzo\src\twig\extension\user
        arguments:
            - '@auth'
            - '@user'
        tags:
            - { name: twig.extension }

    ganstaz.gzo.form.extension:
        class: ganstaz\gzo\src\twig\extension\form
        tags:
            - { name: twig.extension }

    ganstaz.gzo.environment:
        class: ganstaz\gzo\src\twig\phpbb_environment
        decorates: template.twig.environment
        arguments:
            - '@ganstaz.gzo.blocks.data'
            - '@config'
            - '@filesystem'
            - '@path_helper'
            - '%core.template.cache_path%'
            - '@ext.manager'
            - '@template.twig.loader'
            - '@dispatcher'
            - []
        calls:
            - [setLexer, ['@template.twig.lexer']]

    ganstaz.gzo.extensions.phpbb:
        class: ganstaz\gzo\src\twig\phpbb_extension
        decorates: template.twig.extensions.phpbb
        arguments:
            - '@template_context'
            - '@template.twig.environment'
            - '@language'
